apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
  - port: ${GATEWAY_PORT}
    targetPort: ${GATEWAY_PORT}
    nodePort: 30000
  selector:
    app: api-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: yelmach/api-gateway-app:latest
        ports:
        - containerPort: ${GATEWAY_PORT}
        envFrom:
        - secretRef:
            name: rabbit-queue-secrets
        env:
        - name: INVENTORY_API_URL
          value: ${INVENTORY_API_URL}
        - name: RABBITMQ_HOST
          value: "${RABBITMQ_HOST}"
        - name: RABBITMQ_PORT
          value: "${RABBITMQ_PORT}"
        - name: GATEWAY_HOST
          value: "${GATEWAY_HOST}"
        - name: GATEWAY_PORT
          value: "${GATEWAY_PORT}"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60