apiVersion: v1
kind: Service
metadata:
  name: inventory-db-service
  labels:
    app: inventory-db
spec:
  ports:
  - port: ${INVENTORY_DB_PORT}
    targetPort: ${INVENTORY_DB_PORT}
  selector:
    app: inventory-db
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  serviceName: inventory-db-service
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: inventory-db
        image: yelmach/inventory-db:latest
        ports:
        - containerPort: ${INVENTORY_DB_PORT}
        envFrom:
        - secretRef:
            name: inventory-db-secrets
        volumeMounts:
        - name: inventory-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: inventory-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi