apiVersion: v1
kind: Service
metadata:
  name: inventory-app-service
  labels:
    app: inventory-app
spec:
  ports:
  - port: ${INVENTORY_PORT}
    targetPort: ${INVENTORY_PORT}
  selector:
    app: inventory-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: yelmach/inventory-app:latest
        ports:
        - containerPort: ${INVENTORY_PORT}
        envFrom:
        - secretRef:
            name: inventory-app-secrets
        env:
        - name: INVENTORY_DB_HOST
          value: "${INVENTORY_DB_HOST}"
        - name: INVENTORY_DB_PORT
          value: "${INVENTORY_DB_PORT}"
        - name: INVENTORY_HOST
          value: "${INVENTORY_HOST}"
        - name: INVENTORY_PORT
          value: "${INVENTORY_PORT}"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60