apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secrets
type: Opaque
stringData:
  BILLING_DB_USER: "$BILLING_DB_USER"
  BILLING_DB_PASSWORD: "$BILLING_DB_PASSWORD"
  BILLING_DB_NAME: "$BILLING_DB_NAME"

---

apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secrets
type: Opaque
stringData:
  INVENTORY_DB_USER: "$INVENTORY_DB_USER"
  INVENTORY_DB_PASSWORD: "$INVENTORY_DB_PASSWORD"
  INVENTORY_DB_NAME: "$INVENTORY_DB_NAME"